[build]
  command = "npm install" # or "yarn install"
  publish = "public" # or the directory where your static files are located

[functions]
  directory = "api"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Origin = "*"
