[build]
  command = "npm install" # or "yarn install" if using Yarn

[functions]
  directory = "api"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Origin = "*"
