[build]
  command = "npm install" # Or "yarn install" if using Yarn
  publish = "public" # If you have a frontend; otherwise, you can remove this

[functions]
  directory = "api"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Origin = "*"
